### PR TITLE
Scopes

### PR DESCRIPTION
**Pull request by alex-phillips**
Adds support for defining the `scope` of the account before authorization.

### CODE REVIEW

**Comment by therealssj** [comment]
But we do not have the ability to set scopes if we use command line right? unless we modify the files..

**Comment by Mwesome** [comment]
We do not*

**Comment by alex-phillips** [comment]
Right. The command line implementation is supposed to be a utility for managing the remote service almost as if it were a file system. I don't really know why you wouldn't want to limit this tool.

**Comment by therealssj** [comment]
Aah nothing. I was just asking that because somewhere it was still dependent on the scope set in the code. If amazon were to change the scopes again you would have to edit the code to make it work.

**Comment by alex-phillips** [comment]
Right. The CLI is an implementation using the SDK provided. While you can use the CLI inside of a separate project, it's probably best to just build on top of the SDK itself.

That being said, if Amazon decides to change the scopes again, hopefully it will be adding or tweaking syntax in which case no "code" has to be changed, simply the constant variables. And the constants are best because it prevents the developer from having to know what that syntax amazon expects is and from the SDK from having to parse and makes sure they are the proper format.

**Comment by therealssj** [comment]
Ohh right! I see your point now!

**Comment by alex-phillips** [comment]
Anything else you see or have question in the PR? Otherwise, I'll go ahead and merge.

**Pull request merged**
