### PR TITLE
Add forced deletion

### PR DESCRIPTION
**Pull request by nikkiii**
Trashed items can be deleted by sending a `DELETE` request to `https://www.amazon.com/drive/v1/nodes/{id}`, this PR implements it.

### CODE REVIEW

**Comment by nikkiii** [comment]
It looks like the features merged with the other branch too... If you have any suggestions on how to only make it merge the permanent deletion change, I'd be happy to resubmit it if this breaks it in any way.

**Comment by alex-phillips** [comment]
I'll review the stream PR first. Once that gets merged in, just rebase this branch and push it up and the only diff should be the `delete` changes.

As far as permanently deleting a node, I don't see this documented anywhere. How did you find that this endpoint worked?

Thanks for the interest in the project!

**Comment by nikkiii** [comment]
Well, I guess the url isn't correct in the implementation and I was mistaken to think it worked (I tried it and it seemed to, but that might've been a mixup), but it does exist on the frontend and probably exists SOMEWHERE on the other host.

I'm looking into it now, probably going to have to close this and revert it since I don't think it works :(

**Comment by nikkiii** [comment]
After some digging it seems I was mistaken in thinking that it'd work here.

From the developer forums:

```
As of right now permanently deleting content is not available through the Amazon Cloud Drive API.
You can however use the "trash" API to soft delete a node putting contents in the customer's recycle bin.
```

I'll close this since it doesn't work.

**Pull request closed without merging**
