### PR TITLE
Streams

### PR DESCRIPTION
**Pull request by nikkiii**
Adds stream writing/reading support, and fixes the upload field. I'm not sure if it really changed, though `contents` did not work, and changing it to file matched what happened in the web upload and worked.

Also have another pull request for permanent deletion support.

### CODE REVIEW

**Comment by nikkiii** [comment]
I should note that the `uploadStream` function differs from the uploadFile one, in that it uses the remotePath as the full file name, extracting the dirname and basename using pathinfo.

**Comment by alex-phillips** [comment]
This looks good to me, will just need to test it out (may not get to it until this weekend or so).

I have pushed a bug fix or 2 since this PR, if you wouldn't mind rebasing with master I'll get this tested ASAP.

**Comment by nikkiii** [comment]
Not 100% sure if it was done correctly, but that might do it

**Comment by Zn4rK** [comment]
Any plans on merging this soon? Seems to work good for me!

**Comment by alex-phillips** [comment]
Merged, sorry for the delay!

I won't lie, most of my cloud drive work has been on the node version lately. Thanks for the PR!

**Pull request merged**
